const emails = [
    {from: 'john@example.com', 
      to: ['codey@example.com'], 
      subject: 'greeting', 
      attachment: false, 
      date: '2020/01/01 00:35', 
      body: 'hello as per discussed from our last meeting...',
      id: '1'},
    {from: 'mike@example.com', 
      to: ['suzuki@example.com', 'takahashi@example.com', 'yamamoto@example.com', 'yamada@example.com'], 
      attachment: true, 
      subject: 'hello suzuki', 
      date: '2020/02/25 19:35',
      body: 'Thanks for showing interest in our product!',
      id: '2'},
    {from: 'peter@example.com', 
      to: ['zhangyikai@example.com','yijianlian@example.com'], 
      subject: 'did we meet?', 
      attachment: false, 
      date: '2020/03/03 18:35',
      body: 'Last year during September, we met at Harajuku.',
      id: '3'},
    {from: 'aiko@example.com', 
      to: ['shinjuku@example.com', 'me@example.com'], 
      subject: 'regarding the meeting', 
      attachment: true, 
      date: '2020/03/03 18:47',
      body: 'Could you recall what model we decided with our general manager?',
      id: '4'},
    {from: 'kobebryant@example.com', 
      to: ['michaeljordan@example.com'], 
      subject: 'NBA 2k20', 
      attachment: true, 
      date: '2020/01/03 09:35',
      body: 'Playoff 2020 will be a phenomenal game.',
      id: '5'},
    {from: 'disney@example.com', 
      to: ['universaljapan@example.com'], 
      subject: 'announcing new products', 
      attachment: false, 
      date: '2020/01/13 01:40',
      body: 'hello as per discussed from our last meeting...',
      id: '6'},
    {from: 'california@example.com', 
      to: ['hokkaido@example.com'], 
      subject: 'announcing new products', 
      attachment: true, 
      date: '2020/02/28 01:40',
      body: 'hello as per discussed from our last meeting...',
      id: '7'},
    {from: 'xbox@example.com', 
      to: ['google@example.com'], 
      subject: 'announcing new products', 
      attachment: false, 
      date: '2020/04/29 01:40',
      body: 'hello as per discussed from our last meeting...',
      id: '8'},
    {from: 'nintendo@example.com', 
      to: ['facebook@example.com'], 
      subject: 'announcing new products', 
      attachment: true, 
      date: '2018/01/01 01:40',
      body: 'hello as per discussed from our last meeting...',
      id: '9'},
    {from: 'sonic@example.com', 
      to: ['netflix@example.com'], 
      subject: 'announcing new products', 
      attachment: false, 
      date: '2019/06/03 01:40',
      body: 'hello as per discussed from our last meeting...',
      id: '10'}
  ]

export default emails